SIM               = verilator
TOPLEVEL_LANG     = verilog
VERILOG_SOURCES  += ../verilog/*.v ../config.vlt
MODULE            = test_alarm_clock

include $(shell cocotb-config --makefiles)/Makefile.sim
